.TH "fcpredirect" "1" "0.2.1" "aum" "pyfcp - Freenet FCP tools"
.SH "NAME"
.LP 
fcpredirect \- insert a freenet URI, as a redirect to another URI

.SH "SYNOPSIS"
.LP 
\fBfcpredirect\fP [\fIoptions\fP] \fIsrc_uri\fR \fItarget_uri\fR

.SH "DESCRIPTION"
.LP 
fcpredirect is a simple command\-line FCP client program which inserts
a URI into freenet, as a redirect to another URI.

Note the order of arguments \- you specify the 'source' first, and
the 'target' second. This is the opposite of commands
such as 'ln'.

.SH "OPTIONS"
.LP 
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit
.TP 
\fB\-V\fR, \fB\-\-version\fR
Print version number and exit
.TP 
\fB\-v\fR, \fB\-\-verbose\fR
Enable very verbose output, including FCP transcripts,
to the stderr stream.
.TP 
\fB\-H\fR, \fB\-\-fcpHost=<hostname>\fR
Use FCP interface at host <hostname>,
defaults to 127.0.0.1
.TP 
\fB\-P\fR, \fB\-\-fcpPort=<port>\fR
Use FCP interface at port <port>
.LP 

.SH "FILES"
.TP 
\fBnone\fP
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBFCP_HOST\fP
Specifies the hostname of the FCP interface. This value
will be used unless overridden with '\-H'.
.TP 
\fBFCP_PORT\fP
Specifies the port number of the FCP interface. This value
will be used unless overridden with '\-P'.

.LP 

.SH "EXAMPLES"
.TP 
\fBfcpredirect KSK@glitters KSK@gold\fR

Inserts a new key \fBKSK@glitters\fR, which when retrieved redirects
to the key \fBKSK@gold\fR

.LP 

.SH "AUTHORS"
.LP 
aum <david@rebirthing.co.nz>
.SH "SEE ALSO"
.LP 
fcpget(1) fcpput(1) freesitemgr(1) fcpinvertkey(1) fcpgenkey(1)


