.TH "fproxyproxy" "1" "0.2.2" "aum" "pyfcp - Freenet FCP tools"
.SH "NAME"
.LP 
fproxyproxy \- a name\-service\-enabled http proxy service over fproxy

.SH "SYNOPSIS"
.LP 
\fBfproxyproxy\fP [\fIoptions\fP]
.SH "DESCRIPTION"
.LP 
\fBfproxyproxy\fR is an http proxy server that sits on top of
Freenet's FProxy server. It translates human\-friendly
freenet 'domain names' received from the client into proper
freenet URIs, feeds these URIs into fproxy, and feeds FProxy's
output back to the client.

Whereas FProxy is designed to be used as a web server,
fproxyproxy is designed to be configured into the browser as
an http proxy server. Fortunately, with excellent quick
proxy\-switching features of modern browsers (such as the
\fBSwitchProxy\fR extension in \fBFirefox\fR), this
becomes an easy and simple operation.

As an example of the use of fproxyproxy,
if you had a 'freenet name services' record
for the 'pyfcp' website, you would be able to type
\fBhttp://pyfcp\fR
into your browser, and be viewing the pyfcp freesite! (As long
as you have set up fproxyproxy as an http proxy in your web browser).

fproxyproxy is a proof of concept for using secure, human\-friendly
freesite addresses within freenet, and is intended to be used
alongside the \fBfcpnames(1)\fR utility.

If you want to access FProxy directly in a browser configured to use
fproxyproxy as a proxy server, just enter the address
\fBhttp://fproxy\fR.

.SH "OPTIONS"
.LP 
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit
.TP 
\fB\-V\fR, \fB\-\-version\fR
Print version number and exit
.TP 
\fB\-v\fR, \fB\-\-verbose\fR
Enable very verbose output, including FCP transcripts,
to the stderr stream.
.TP 
\fB\-H\fR, \fB\-\-fcpHost=\fIhostname\fR
Use FCP interface at host \fIhostname\fR,
defaults to \fB127.0.0.1\fR
.TP 
\fB\-P\fR, \fB\-\-fcpPort=\fIport\fR
Use FCP interface at port \fIport\fR
.TP 
\fB\-p\fR, \fB\-\-fproxyAddress=\fI[hostname][:port]\fR
Point fproxyproxy at the FProxy service at address
\fIhostname:port\fR, default is \fB127.0.0.1:8888\fR.
.TP 
\fB\-L\fR, \fB\-\-listenAddress=\fI[hostname][:port]\fR
Sets the address fproxyproxy listens on for client http
connections, default is \fB127.0.0.1:8889\fR.

.LP 

.SH "FILES"
.TP 
\fBnone\fP
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBFCP_HOST\fP
Specifies the hostname of the FCP interface. This value
will be used unless overridden with '\-H'.
.TP 
\fBFCP_PORT\fP
Specifies the port number of the FCP interface. This value
will be used unless overridden with '\-P'.

.LP 

.SH "EXAMPLES"
.TP 
\fBfproxyproxy \-L localhost:2225 \-p 192.168.1.5\fP
Run fproxyproxy, listening for client connections on
\fBlocalhost:2225\fR, and forwarding requests to
an FProxy port at \fB192.168.1.5:8888\fR (note the
default 8888 being applied to fproxy port).

.LP 

.SH "AUTHORS"
.LP 
aum <david@rebirthing.co.nz>
.SH "SEE ALSO"
.LP 
fcpnames(1)


