.TH "freesitemgr" "1" "0.1.4" "aum" "pyfcp - Freenet FCP tools"
.SH "NAME"
.LP 
freesitemgr \- Insert or re\-insert freesites into freenet

.SH "SYNTAX"
.LP 
\fBfreesitemgr\fP [\fIoptions\fP] \fIcommand\fP [\fIarguments\fP]
.SH "DESCRIPTION"
.LP 
\fBfreesitemgr\fP is a simple command\-line freenet client program
for inserting \fBfreesites\fP.

Use of this program is controlled by the \fIcommand\fP argument
you give it.

run \fBfreesitemgr \-h\fP for a detailed help output.
.SH "OPTIONS"
.LP 
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit
.TP 

\fB\-v\fR, \fB\-\-verbose\fR
Enable very verbose output, including FCP transcripts,
to the stderr stream.
.TP 

\fB\-q\fR, \fB\-\-quiet\fR
Run quietly
.TP 

\fB\-l\fR, \fB\-\-logfile\fR
location of logfile (default /home/david/updatesites.log)
.TP 

\fB\-s\fR, \fB\-\-single\-files\fR
Insert each file of the freesite as single CHKs, and redirect
to these from within the freesite manifest. You \fBmust\fR use
this option if inserting through an FCP port not on your local machine.
Note that files will be inserted one at a time, with each next file
not being inserted till the previous one is completely inserted. If you
wish to insert more than one file concurrently, use the \fB\-a\fR
or \fB\-m\fR options.
.TP 

\fB\-a\fR, \fB\-\-all\-at\-once\fR
Enables concurrent insert of the site's files. By default, a maximum
of 10 files will be inserting at any one time. You can increase this with
\fB\-m\fR. Note that this \fB\-a\fR option automatically turns on
\fB\-s\fR.
.TP 

\fB\-m\fR, \fB\-\-max\-concurrent\-inserts=\fR\fInum\fR
Turns on \fB\-s\fR and \fB\-a\fR, and sets the maximum number
of concurrent file inserts to \fInum\fR. You can set a very high
value if you want, but it will be of little use because the node
itself regulates how many concurrent inserts it performs.
.TP 

\fB\-i\fR, \fB\-\-insert\-all\fR
Forces insert of all files in all aites. Otherwise, sites with no new
or changed files will be skipped, and in sites that have changed,
only the new/changed files (and a fresh manifest) will be inserted.

.LP 

.SH "COMMANDS"
\fBsetup\fP
Create or modify the freesite config file (\fB~/.freesites\fP)
interactively.

\fBadd\fP
Add a new freesite interactively

\fBlist [<name>]\fP
display a summary of all freesites, or a
detailed report of one site if <name> given

\fBremove <name>\fP
remove given freesite

\fBupdate\fP
reinsert any freesites which have changed since
they were last inserted


.LP 

.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBFCP_HOST\fP
Specifies the hostname of the FCP interface. This value
will be used unless overridden with '\-H'.
.TP 
\fBFCP_PORT\fP
Specifies the port number of the FCP interface. This value
will be used unless overridden with '\-P'.

.LP 

.SH "AUTHORS"
.LP 
aum <david@rebirthing.co.nz>
.SH "SEE ALSO"
.LP 
fcpget(1) fcpput(1) fcpgenkey(1)

