.TH "freesitemgr" "1" "0.1.4" "aum" "pyfcp - Freenet FCP tools"
.SH "NAME"
.LP 
freesitemgr \- Insert or re\-insert freesites into freenet

.SH "SYNTAX"
.LP 
\fBfreesitemgr\fP [\fIoptions\fP] \fIcommand\fP [\fIarguments\fP]
.SH "DESCRIPTION"
.LP 
\fBfreesitemgr\fP is a simple command\-line freenet client program
for inserting \fBfreesites\fP.

Use of this program is controlled by the \fIcommand\fP argument
you give it.

run \fBfreesitemgr \-h\fP for a detailed help output.

Note that this is a new, rewritten version of freesitemgr, designed
to be extremely fault\-tolerant. If you interrupt freesitemgr,
or if the freenet node dies, halfway through an insert, then you can
simply re\-run freesitemgr, and it will pick up where it left off.
This new resilience is a response to public demand, and the needs
of users wanting to insert large freesites with high file counts.

.SH "OPTIONS"
.LP 
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit
.TP 

\fB\-c\fR, \fB\-\-config\-dir=\fR
Sets config directory (default ~/.freesitemgr/)
.TP 

\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output to the stderr stream. Can be given
twice to enable FCP transcripts, or more to enable more
detailed debugging information
.TP 

\fB\-q\fR, \fB\-\-quiet\fR
Run quietly
.TP 

\fB\-l\fR, \fB\-\-logfile\fR
location of logfile (default stdout)
.TP 

\fB\-m\fR, \fB\-\-max\-concurrent\-inserts=\fR\fInum\fR
sets the maximum number
of concurrent file inserts to \fInum\fR. You can set a very high
value if you want, but it will be of little use because the node
itself regulates how many concurrent inserts it performs.

.LP 

.SH "COMMANDS"
\fBsetup\fP
Create or modify the freesite config file (\fB~/.freesitemgr/.config\fP)
interactively.

\fBadd\fP
Add a new freesite interactively

\fBlist [<name>]\fP
display a summary of all freesites, or a
detailed report of one site if <name> given

\fBremove <name>\fP
remove given freesite

\fBupdate\fP
reinsert any freesites which have changed since
they were last inserted


.LP 

.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBFCP_HOST\fP
Specifies the hostname of the FCP interface. This value
will be used unless overridden with '\-H'.
.TP 
\fBFCP_PORT\fP
Specifies the port number of the FCP interface. This value
will be used unless overridden with '\-P'.

.LP 

.SH "AUTHORS"
.LP 
aum <david@rebirthing.co.nz>
.SH "SEE ALSO"
.LP 
fcpget(1) fcpput(1) fcpgenkey(1)

